version: "3.8"

services:
  app:
    container_name: project-package-initializer
    image: company/project-package-initializer:1.0.0
    build:
      context: .
      target: production
    ports:
      - 3000:80